# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin

export JAVA_HOME=/usr/java/jdk1.7.0_25/
export HADOOP_HOME=/home/hadoop/hadoop/
PATH=$JAVA_HOME/bin:$HADOOP_HOME/bin:$PATH

export PATH
